############################################################################
# apps/examples/ok8mp_gpio_test/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_GPIO_TEST_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_OK8MP_GPIO_TEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_OK8MP_GPIO_TEST_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_OK8MP_GPIO_TEST)

MAINSRC = ok8mp_gpio_test_main.c

include $(APPDIR)/Application.mk
