############################################################################
# apps/examples/ok8mp_voice/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_VOICE_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_OK8MP_VOICE_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_OK8MP_VOICE_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_OK8MP_VOICE)

MAINSRC = ok8mp_voice_main.c

include $(APPDIR)/Application.mk
