############################################################################
# apps/examples/ok8mp_can_ecu/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_CAN_ECU_PROGNAME)
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_EXAMPLES_OK8MP_CAN_ECU)
MAINSRC   = ok8mp_can_ecu_main.c

include $(APPDIR)/Application.mk
