############################################################################
# apps/examples/ok8mp_net_proxy/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_NET_PROXY_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_OK8MP_NET_PROXY_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_OK8MP_NET_PROXY_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_OK8MP_NET_PROXY)

MAINSRC = ok8mp_net_proxy_main.c

include $(APPDIR)/Application.mk
