############################################################################
# apps/examples/ok8mp_fec_probe/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_FEC_PROBE_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_OK8MP_FEC_PROBE_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_OK8MP_FEC_PROBE_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_OK8MP_FEC_PROBE)

MAINSRC = ok8mp_fec_probe_main.c

include $(APPDIR)/Application.mk
