############################################################################
# apps/examples/ok8mp_can_diagnostic/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_CAN_DIAGNOSTIC_PROGNAME)
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = CONFIG_DEFAULT_TASK_STACKSIZE
MODULE    = $(CONFIG_EXAMPLES_OK8MP_CAN_DIAGNOSTIC)
MAINSRC   = ok8mp_can_diagnostic_main.c

include $(APPDIR)/Application.mk
