############################################################################
# apps/examples/ok8mp_can_monitor/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_OK8MP_CAN_MONITOR_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_OK8MP_CAN_MONITOR_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_OK8MP_CAN_MONITOR_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_OK8MP_CAN_MONITOR)
MAINSRC   = ok8mp_can_monitor_main.c

include $(APPDIR)/Application.mk
